### ISSUE TITLE
Ignore specific error on specific contract

### ISSUE THREAD

**Issue by somoza** [dmuhs/mythx-cli#283]
I'm getting this result:

```
Report for node_modules/@openzeppelin/contracts/interfaces/draft-IERC1822.sol
(SWC-112) Delegatecall to Untrusted Callee
```

I would like to know if I can ignore that error on that contract using mythx.yml, for example:

```
ignore:
  - SWC-112:
    contracts:
      - node_modules/@openzeppelin/contracts/interfaces/draft-IERC1822.sol
```

Is there some way to ignore errors on specific contracts without using blacklists that ignore an error on all the contracts?

Thanks!
